### ISSUE TITLE
doesn't work with mist

### ISSUE THREAD

**Issue by elopio** [coopermaruyama/react-web3#28]
I'm trying to change my custom account loader to react-web3. I added the <Web3Provider> and everything seems to work nicely on metamask, but it is not working on mist:

![ekrankopio de 2018-04-21 18-31-07](https://user-images.githubusercontent.com/617831/39090108-bd874fe0-4592-11e8-8793-1cce6b6b18ae.png)
![ekrankopio de 2018-04-21 18-31-44](https://user-images.githubusercontent.com/617831/39090109-c350e7f6-4592-11e8-9895-0676d1b070a7.png)

Here is the source for my dapp:
https://github.com/elopio/dapp/tree/refactor/10/react-web3

**Comment by coopermaruyama** [comment]
@elopio Have not messed with mist in a while but will do my best to help you. Just launched it up now and noticed you have to explicitly give a dapp access to your account. Had that been done here in this screenshot? Weird that it doesnt work because I just tried `web3.eth.getAccounts()` in the console and it worked (which is the same call this lib makes)
